spring:
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password: 
    url: jdbc:h2:file:~/test
  h2:    console:      enabled: true      path: /h2  jpa:    hibernate:      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: GMT      

   
   